config/routes.rb
Blog::Application.routes.draw do
  get "sessions/new"
  get "users/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :users do
    member do
      get :follow
      get :alluser
    end
  end
  match '/signup',  :to => 'users#new'
  match '/signout', :to => 'sessions#destroy'

   root :to => 'sessions#new'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
 attr_accessible :content
 belongs_to :user

 validates :content, :presence => true, :length => { :maximum => 140 }
 validates :user_id, :presence => true

 default_scope :order => 'microposts.created_at DESC'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id

  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
 attr_accessible :name, :email

  has_many :microposts, :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
 
 validates :name, :presence => true,
                  :length   => { :maximum => 50 },
                  :uniqueness =>true
 validates :email, :presence => true,
                   :uniqueness => { :case_sensitive => false }

 def has_email?(submitted_email)
  email == submitted_email
 end

 def self.authenticate(name, submitted_email)
    user = find_by_name(name)
    if user.nil?
       return nil
    end
   if user.has_email?(submitted_email)
     return user
   end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  def create
  @user = User.find(params[:user_id])
    @micropost  = @user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
   redirect_to @user
      
    else
      render 'pages/home'
    end
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   @title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:name],
                             params[:session][:email])
    if user.nil?
      flash.now[:error] = "Invalid name/email combination."
      @title = "Sign in"
      render 'new'
    else
      redirect_to user
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def show
    @user = User.find(params[:id])
    @micropost = Micropost.new
    @microposts = @user.microposts
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
    @users = User.all
  end
   
  def alluser
   @user = User.find(params[:id])
   @users = User.all
  end

  def follow
   @user = User.find(params[:id])
   @micropost=Micropost.where(user_id:[@user.following_ids])	
  end

  def create
    @user = User.new(params[:user])
    if @user.save
       redirect_to @user
      # Обработка успешного сохранения.
    else
      @title = "Sign up"
      render 'new'
    end
  end

  def update
   @user = User.find(params[:current_user_id])
   @abc=User.find(params[:user_id])
   if @user.following_ids.include?(@abc.id)
     @user.relationships.find_by_followed_id(params[:user_id]).destroy
   else
     @user.relationships.create(:followed_id =>params[:user_id])
    end
 redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
</tr>
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/microposts/new.html.erb
<h1>Microposts#new</h1>
<p>Find me in app/views/microposts/new.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/alluser.html.erb
<strong>Name</strong> <%= @user.name %><br />
<% @users.each do |user| %>
  <%if user.id!=@user.id%>
    <li>
      <%=user.name%>
        <%= form_for user do |f| %>
         <%= hidden_field_tag(:user_id, user.id) %>
         <%= hidden_field_tag(:current_user_id, @user.id) %>
         <% if @user.following_ids.include?(user.id)%>
           <%= f.submit "Не читать" %>
          <%else%>
           <%= f.submit "Читать" %>          
         <% end %>
        <% end %>
    </li>
   <% end %>
  <% end %>

app/views/users/follow.html.erb
<strong>Name</strong> <%= @user.name %><br />

  <% @micropost.each do |micropost| %>
  <%@username = User.find(micropost.user_id)[:name] %> 
  <strong> <%=@username%></strong></br>
  <%=micropost.content %></br>
  <%end%>

app/views/users/new.html.erb
<h1>Регистрация</h1>
<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :имя %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
 <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table>
    <tr>
       <tb> <strong>Name</strong> <%= @user.name %></tb>
       <tb>    <%=link_to "Все пользователи", alluser_user_path(@user)%></tb>
       <tb><a href="<%= follow_user_path(@user) %>">   Читаемые пользователи</a></tb></tr></table>
       <tr><strong>Microposts</strong> <%= @user.microposts.count %></tr>
<h2>Microposts</h2>
  <% @microposts.each do |microposts| %>
      <%= microposts.content %>
      <hr>
  <% end %>
      <td class="sidebar round">
    </td>
Создать сообщение
<%= form_for @micropost do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">    
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= hidden_field_tag(:user_id, @user.id) %></br>
  </div>
  <div class="actions">
    <%= f.submit "Отправить" %>
  </div>
<% end %>


 